# Generated by Django 4.2.27 on 2026-01-31 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriapp', '0002_alter_crop_id_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
